openapi: 3.0.0
info:
  title: JupyterLab HDF5 proxy
  description: Proxies HDF5 API requests from JupyterLab to HDF5.
  version: 0.0.1
  
paths:
  /hdf/meta/{fpath}:
    get:
      summary: Gets the metadata at the apiPath for the HDF5 API.
      parameters:
        - name: fpath
          in: path
          required: true
          description: "Path on disk to an HDF5 file."
          schema:
            type: string
            format: uri
        - name: uri
          in: query
          description: "Path within an HDF5 file to a specific group or dataset."
          schema:
            type: string
        - name: rowSlice
            in: query
            description: "Row slice (eg '30:45')."
            schema:
              type: string
        - name: colSlice
            in: query
            description: "Col slice (eg '30:45')."
            schema:
              type: string
        - name: rows
          in: query
          description: "Slice defined by one or more integers."
          schema:
            type: array
            style: pipeDelimited
            explode: false
            items:
              type: integer
      responses:
        '200':
          description: Found hdf file, got metadata.
          schema:
            type: array
            items:
              type: object
              properties:
                type:
                  type: string
                name:
                  type: string
                uri:
                  type: string
        '400':
          description: The request was malformed; should be of the format "<file-path>::<uri-path>"
        '401':
          description: The request did not specify a file that `h5py` could understand.
        '403':
          description: The request specified a file that did not exist.
        '500':
          description: Found and opened file, error getting metadata.
