# jupyterLab_hdf : HDF5 api for Jupyter/Jupyterlab
#
# Copyright (c) Max Klein.
# Distributed under the terms of the Modified BSD License.

openapi: 3.0.0
info:
  title: JupyterLab HDF5 proxy
  description: Proxies HDF5 API requests from JupyterLab to HDF5.
  version: 0.1.0-alpha
components:
  parameters:
    - name: fpath
      in: path
      required: true
      description: "Path on disk to an HDF5 file."
      schema:
        type: string
        format: uri
    - name: uri
      in: query
      required: true
      description: "Path within an HDF5 file to a specific group or dataset."
      schema:
        type: string
    - name: chunk
      in: query
      description: "The size of the data chunk to fetch."
      schema:
        type: integer
        default: 1
    - name: row
      in: query
      description: "Row slice. Will be in units of chunk size. Up to 3 integers, same syntax as for Python `slice` built-in."
      explode: false
      schema:
        type: array
        items:
          type: integer
        nullable: true
        maxItems: 3
    - name: col
      in: query
      description: "Column slice. Will be in units of chunk size. Up to 3 integers, same syntax as for Python `slice` built-in."
      explode: false
      schema:
        type: array
        items:
          type: integer
        nullable: true
        maxItems: 3

paths:
  /hdf/contents/{fpath}{?uri,chunk,row,col}:
    get:
      summary: Get the contents of the hdf object pointed to by the uri in the file at fpath.
      parameters:
        - $ref: '#/components/parameters/fpath'
        - $ref: '#/components/parameters/uri'
        - $ref: '#/components/parameters/chunk'
        - $ref: '#/components/parameters/row'
        - $ref: '#/components/parameters/col'
      responses:
        '200':
          description: Found hdf object, got contents.
          schema:
            type: array
            items:
              type: object
              properties:
                type:
                  type: string
                name:
                  type: string
                uri:
                  type: string
                content:
                  type: string
        '400':
          description: The request was malformed; should be of the format "file/path?uri=uri/path&chunk=int&row=[start,stop,step]&col=[start,stop,step]"
        '401':
          description: The request did not specify a file that `h5py` could understand.
        '403':
          description: The request specified a file that does not exist.
        '500':
          description: Found and opened file, error getting contents from object specified by the uri.

  /hdf/data/{fpath}{?uri,chunk,row,col}:
    get:
      summary: Get chunks of data from the hdf dataset pointed to by the uri in the file at fpath.
      parameters:
        - $ref: '#/components/parameters/fpath'
        - $ref: '#/components/parameters/uri'
        - $ref: '#/components/parameters/chunk'
        - $ref: '#/components/parameters/row'
        - $ref: '#/components/parameters/col'
      responses:
        '200':
          description: Found hdf dataset, got data.
          schema:
            type: string
        '400':
          description: The request was malformed; should be of the format "file/path?uri=uri/path&row=[start,stop,step]&col=[start,stop,step]"
        '401':
          description: The request did not specify a file that `h5py` could understand.
        '403':
          description: The request specified a file that does not exist.
        '500':
          description: Found and opened file, error getting data from dataset specified by the uri.
