openapi: 3.0.0
info:
  title: JupyterLab HDF5 proxy
  description: Proxies HDF5 API requests from JupyterLab to HDF5.
  version: 0.0.1
  
paths:
  /hdf5/{apipath}:
    get:
      summary: Gets the metadata at the apiPath for the HDF5 API.
      parameters:
        - name: apipath
          in: apipath
          required: true
          description: API path for HDF5.
          schema:
            type: string
            format: uri
      responses:
        '200':
          description: Found hdf file, got metadata.
          schema:
            type: array
            items:
              type: object
              properties:
                kind:
                  type: string
                name:
                  type: string
                uri:
                  type: string
        '400':
          description: The request did not specify a file that `h5py` could understand.
        '403':
          description: The request specified a file that did not exist.
        '500':
          description: Found and opened file, error getting metadata.
